import { chromium } from '@playwright/test';
import { build } from 'vite';
import react from '@vitejs/plugin-react';
import { readFile, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { buildPreviewBridge } from '../../lib/preview-bridge';

const origin = 'http://localhost:8790';
const report = { scope:'Actual PreviewFrame, preview bridge and LiveInspector in cross-origin Chromium. Synthetic DOM fixture; NOT private import, source mapping, paid AI, production parity or WebContainer acceptance.', checks:[] as string[], errors:[] as string[], failure:undefined as string | undefined, maxSnapshotBytes:0, iframeNavigations:0 };
await build({ configFile:false, plugins:[react()], define:{'process.env.NODE_ENV':'"production"'}, logLevel:'error', build:{outDir:'outputs/audit/inspection-dist',emptyOutDir:true,rollupOptions:{output:{inlineDynamicImports:true}},lib:{entry:'tests/browser/inspection-fixture.tsx',formats:['es'],fileName:()=>'fixture.js',cssFileName:'fixture'}} });
const js = await readFile('outputs/audit/inspection-dist/fixture.js','utf8');
const css = await readFile('outputs/audit/inspection-dist/fixture.css','utf8');
const browser = await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try {
  const context = await browser.newContext({viewport:{width:1200,height:1000}});
  await context.route('**/*', async route => {
    const url = new URL(route.request().url());
    if (url.origin === 'http://127.0.0.1:8793') {
      report.iframeNavigations++;
      return route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><style>body{font:16px system-ui;margin:32px;min-height:2800px}h1{font:32px Georgia}button{border-radius:0;background:#315efb;color:white;padding:12px 24px;font:16px system-ui}#nested{height:90px;overflow:auto;margin-top:20px;border:1px solid gray}#nested p{height:900px}</style></head><body><h1>Welcome to your workspace</h1><button id="target" onclick="window.clicks=(window.clicks||0)+1">Create project</button><p id="description">A real page, not a mock card.</p><input type="password" value="fixture-secret-password"><textarea>fixture-secret-textarea</textarea><span data-private>fixture-secret-private</span><div id="nested"><p>Scrollable content</p></div><div id="lots">${Array.from({length:300},(_,i)=>`<p>Layer ${i}</p>`).join('')}</div><script>${buildPreviewBridge(origin)}</script></body></html>`});
    }
    if (url.origin !== origin) return route.abort();
    if (url.pathname === '/fixture.js') return route.fulfill({contentType:'text/javascript',body:js});
    if (url.pathname === '/fixture.css') return route.fulfill({contentType:'text/css',body:css});
    if (url.pathname === '/') return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><link rel="stylesheet" href="/fixture.css"></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>'});
    return route.abort();
  });
  const page = await context.newPage(); page.setDefaultTimeout(15000); page.on('pageerror', error => report.errors.push(error.message));
  await page.goto(origin,{waitUntil:'networkidle'});
  const snapshot = async () => { const raw = await page.locator('#inspection').textContent(); report.maxSnapshotBytes=Math.max(report.maxSnapshotBytes,Buffer.byteLength(raw ?? '')); return JSON.parse(raw ?? 'null'); };
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')?.textContent ?? 'null')?.layers.length === 200);
  assert.equal((await snapshot()).truncated, true);
  assert.ok(!JSON.stringify(await snapshot()).includes('fixture-secret'));
  report.checks.push('Layer traversal bounded to 200; form values and explicitly private DOM excluded');
  const frame = page.frameLocator('iframe[title="First page"]');
  await frame.locator('#target').click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.selection?.text === 'Create project');
  const current = await snapshot();
  assert.equal(current.selection.styles.borderRadius,'0px'); assert.equal(current.selection.styles.fontSize,'16px');
  assert.equal(await frame.locator('body').evaluate(() => (window as Window & { clicks?:number }).clicks ?? 0),0);
  await page.getByRole('button',{name:'Copy element text',exact:true}).focus();
  await page.getByRole('tooltip').waitFor();
  assert.match(await page.getByRole('tooltip').innerText(),/not its source/);
  const hint = await page.getByRole('tooltip').boundingBox();
  assert.ok(hint && hint.x >= 0 && hint.x + hint.width < (await page.locator('aside').boundingBox())!.x + 40);
  assert.equal(await page.getByRole('tooltip').evaluate(el => {const rect=el.getBoundingClientRect();return document.elementFromPoint(rect.x+rect.width/2,rect.y+rect.height/2)?.closest('[role=tooltip]')===el;}),true,'Tooltip escapes scroll clipping');
  await page.keyboard.press('Escape');
  await page.screenshot({path:'outputs/audit/live-inspector-design.png'});
  report.checks.push('Edit selects actual button without its click action; computed radius and typography shown; accessible focus tooltip');
  await page.getByRole('button',{name:'Layers',exact:true}).click();
  await page.getByRole('navigation',{name:'Live page elements'}).getByRole('button',{name:/h1.*Welcome/}).click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.selection?.tag === 'h1');
  assert.equal((await snapshot()).selection.styles.fontSize,'32px');
  assert.equal(await frame.locator('[data-ah-inspector]').count(),1);
  await page.screenshot({path:'outputs/audit/live-inspector-layers.png'});
  report.checks.push('Actual hierarchy selects headline and highlights matching live DOM element');
  await frame.locator('#nested').evaluate(el => { el.scrollTop=200; window.scrollTo(0,400); });
  assert.equal(await frame.locator('body').evaluate(() => scrollY),400);
  assert.equal(await frame.locator('#nested').evaluate(el => el.scrollTop),200);
  assert.equal(report.iframeNavigations,1);
  report.checks.push('Window and nested scrolling stay active in Edit mode; inspection and mode changes do not reload');
  await frame.locator('body').evaluate(() => scrollTo(0,0));
  await page.getByRole('button',{name:'Interact',exact:true}).click();
  await frame.locator('[data-ah-inspector]').waitFor({state:'detached'});
  await frame.locator('#target').click();
  assert.equal(await frame.locator('body').evaluate(() => (window as Window & { clicks?:number }).clicks),1);
  report.checks.push('Interact mode removes highlight and permits actual application click behavior (not a route-navigation test)');
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await frame.locator('#target').click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.selection?.text === 'Create project');
  await frame.locator('#target').evaluate(el => { (el as HTMLElement).style.borderRadius='24px'; });
  await page.getByRole('button',{name:'Refresh elements',exact:true}).click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.selection?.styles.borderRadius==='24px');
  await frame.locator('#target').evaluate(el => el.remove());
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.selection===null);
  report.checks.push('Explicit refresh reads changed styles; removed selection is cleared within one second');
  await page.getByRole('button',{name:'Add comparison',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('iframe').length===2);
  await page.evaluate(() => addEventListener('message', event => { if(event.data?.type==='agent-harness:inspection' && event.data?.inspection?.layers[0]?.label==='FORGED') (window as Window & { forgedDelivered?:boolean }).forgedDelivered=true; }));
  await page.frameLocator('iframe[title="Second page"]').locator('body').evaluate((_el,data) => parent.postMessage({type:'agent-harness:inspection',frameId:'first',inspection:{...data,layers:data.layers.map((node: { label:string },index:number)=>index===0?{...node,label:'FORGED'}:node)}},'http://localhost:8790'), await snapshot());
  await page.waitForFunction(() => (window as Window & { forgedDelivered?:boolean }).forgedDelivered);
  assert.notEqual((await snapshot()).layers[0].label,'FORGED');
  const generation=(await snapshot()).generation;
  await page.getByRole('button',{name:'Reload frame',exact:true}).click();
  await page.waitForFunction(old => {const value=JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null');return value && value.generation!==old;},generation);
  const priorCapture=(await snapshot()).capturedAt;
  await page.getByRole('button',{name:'Stale selection',exact:true}).click();
  await page.getByRole('button',{name:'Refresh elements',exact:true}).click();
  await page.waitForFunction(old => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.capturedAt!==old,priorCapture);
  assert.equal((await snapshot()).selection,null);
  report.checks.push('Sibling frame messages rejected; document generations reset on reload and stale layer commands ignored');
  await page.getByRole('navigation',{name:'Live page elements'}).getByRole('button',{name:/^body\s*body$/}).click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.selection?.tag==='body');
  assert.ok(!JSON.stringify(await snapshot()).includes('fixture-secret'));
  await frame.locator('body').evaluate(() => {
    document.body.insertAdjacentHTML('afterbegin','<svg><foreignObject></foreignObject></svg>');
  });
  await page.getByRole('button',{name:'Refresh elements',exact:true}).click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#inspection')!.textContent ?? 'null')?.layers.some((node:{tag:string})=>node.tag==='foreignobject'));
  assert.equal((await snapshot()).layers.length,200);
  report.checks.push('Ancestor text extraction excludes private/form descendants; SVG names do not invalidate the snapshot');
  assert.equal(report.errors.length,0);
} catch(error) { report.failure=(error as Error).stack; process.exitCode=1; }
finally { await browser.close(); await writeFile('outputs/audit/live-inspection-results.json',JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2)); }
