import assert from 'node:assert/strict';
import {expect,type Page} from '@playwright/test';
import type {SourceAnchor} from '../../lib/source-anchor';
export async function radiusChecks(page:Page,report:{checks:string[]},source:string,anchor:SourceAnchor){
  const frame=page.frameLocator('iframe[title="Mapped Vite preview"]'),mobile=page.frameLocator('iframe[title="Shared mobile component"]');
  const corners=()=>frame.locator('#action').evaluate(el=>getComputedStyle(el).borderRadius);
  const mobileCorners=()=>mobile.locator('#action').evaluate(el=>getComputedStyle(el).borderRadius);
  const stored=()=>page.evaluate(path=>window.anchorTest.read(path),anchor.file);
  const open=async()=>{await page.getByRole('button',{name:'Refresh elements',exact:true}).click();await page.getByRole('button',{name:'Edit corners',exact:true}).click();await page.getByRole('spinbutton',{name:'Corner radius · px',exact:true}).waitFor();};
  await mobile.locator('#action').waitFor();await page.waitForFunction(()=>!document.querySelector('.frame-runtime-feedback'),{},{timeout:15000});const baseline=await corners(),mobileBaseline=await mobileCorners();
  report.checks.push('The offscreen live comparison completes the actual preview handshake without waiting for visible animation frames');
  await page.getByRole('button',{name:'Interact',exact:true}).click();await frame.locator('#action').click();await page.getByRole('button',{name:'Select',exact:true}).click();
  await open();assert.equal(await page.getByRole('button',{name:'Apply radius',exact:true}).isDisabled(),true);
  await page.getByRole('checkbox',{name:'Override this element at all sizes',exact:true}).check();
  await page.getByRole('spinbutton',{name:'Corner radius · px',exact:true}).fill('24');await page.getByRole('button',{name:'Apply radius',exact:true}).click();
  await page.getByText('Radius verified on this page.',{exact:true}).waitFor();
  assert.equal(await corners(),'24px');assert.equal(await mobileCorners(),'24px');assert.match(await stored(),/borderRadius: 24/);
  assert.equal(await frame.locator('h1').evaluate(el=>getComputedStyle(el).borderRadius),'0px');assert.equal(await frame.locator('output').textContent(),'1');assert.equal(await mobile.locator('output').textContent(),'0');
  report.checks.push('Explicit all-sizes approval is required; actual inspector rounds the selected button to 24px in two viewports through clean JSX/HMR, preserving other elements and independent React state');
  await page.screenshot({path:'outputs/audit/radius-editor.png',timeout:10000});
  await page.getByRole('button',{name:'Undo radius edit',exact:true}).click();await page.getByText('Corners restored.',{exact:true}).waitFor();
  assert.equal(await stored(),source);assert.equal(await corners(),baseline);assert.equal(await mobileCorners(),mobileBaseline);
  report.checks.push('Undo restores byte-exact source and original computed corners in both live variants');
  await page.getByRole('button',{name:'Apply radius',exact:true}).click();await page.getByText('Radius verified on this page.',{exact:true}).waitFor();
  const newer=(await stored()).replace('<h1>Start</h1>','<h1>Newer radius work</h1>');await page.evaluate(text=>window.anchorTest.externalChange(text),newer);await frame.getByRole('heading',{name:'Newer radius work'}).waitFor();
  await page.getByRole('button',{name:'Undo radius edit',exact:true}).click();await page.locator('.mapped-radius-editor [role=alert]').filter({hasText:'Source changed'}).waitFor();
  assert.equal(await stored(),newer);report.checks.push('A newer source edit blocks stale radius Undo without overwriting the newer work');
  await page.getByRole('button',{name:'Close corners',exact:true}).click();await page.evaluate(text=>window.anchorTest.externalChange(text),source);await frame.getByRole('heading',{name:'Start',exact:true}).waitFor();await frame.locator('#action').click();await open();
  await frame.locator('body').evaluate(()=>{const rule=document.createElement('style');rule.id='conflicting-radius';rule.textContent='#action {border-radius:0!important}';document.head.appendChild(rule);});
  await page.getByRole('checkbox',{name:'Override this element at all sizes',exact:true}).check();await page.getByRole('button',{name:'Apply radius',exact:true}).click();
  await expect(frame.locator('#action')).toHaveAttribute('style',/border-radius: 24px/,{timeout:10000});
  await page.waitForTimeout(750);assert.equal(await page.getByText('Radius verified on this page.',{exact:true}).count(),0);assert.equal(await corners(),'0px');
  await page.locator('.mapped-radius-editor [role=alert]').waitFor({timeout:25000});assert.equal(await stored(),source);assert.equal(await mobileCorners(),mobileBaseline);
  report.checks.push('A real !important CSS conflict prevents the requested corners: no success badge, bounded render timeout and exact rollback across both variants');
  await page.screenshot({path:'outputs/audit/radius-conflict.png',timeout:10000});
  await frame.locator('#conflicting-radius').evaluate(el=>el.remove());await page.getByRole('button',{name:'Apply radius',exact:true}).click();await page.getByText('Radius verified on this page.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Undo radius edit',exact:true}).click();await page.getByText('Corners restored.',{exact:true}).waitFor();assert.equal(await stored(),source);
  assert.equal(await page.evaluate(()=>window.anchorTest.diagnostics()?.processes),1);
  report.checks.push('After the conflict is removed, retry and Undo succeed without a second runtime or dev process');
}
