// Preview-only browser instrumentation. It never modifies repository files.
// The parent origin is provided by the trusted host, never inferred as '*'.
export function buildPreviewBridge(parentOrigin: string) {
  const origin = new URL(parentOrigin);
  if (!['http:', 'https:'].includes(origin.protocol) || origin.origin !== parentOrigin) throw new Error('Invalid preview parent origin.');
  return String.raw`(() => {
    const expectedOrigin = ${JSON.stringify(parentOrigin)};
    const frameId = new URLSearchParams(location.search).get('__ah_frame');
    if (!frameId || parent === window) return;
    let initialized = false, restoring = false, timer = 0;
    const finite = v => Number.isFinite(v) ? Math.max(0, v) : 0;
    const send = (type, data = {}) => parent.postMessage({ type: 'agent-harness:' + type, frameId, ...data }, expectedOrigin);
    const keyFor = element => {
      for (const attribute of ['data-ah-scroll', 'data-testid', 'id']) {
        const value = element.getAttribute(attribute);
        if (!value || value.length > 240) continue;
        const selector = '[' + attribute + '=' + JSON.stringify(value) + ']';
        try { if (document.querySelectorAll(selector).length === 1) return selector; } catch {}
      }
      return null;
    };
    const snapshot = () => ({
      windowX: finite(scrollX), windowY: finite(scrollY), capturedAt: new Date().toISOString(),
      containers: [...document.querySelectorAll('[data-ah-scroll],[data-testid],[id]')]
        .filter(el => el !== document.scrollingElement && (el.scrollHeight > el.clientHeight || el.scrollWidth > el.clientWidth))
        .flatMap(el => { const anchor = keyFor(el); return anchor ? [{ anchor, x: finite(el.scrollLeft), y: finite(el.scrollTop) }] : []; }).slice(0, 20)
    });
    const report = () => { timer = 0; if (initialized && !restoring) send('scroll', { snapshot: snapshot() }); };
    // Throttle, not debounce: long scrolls still save progress every 100 ms.
    addEventListener('scroll', () => { if (!timer && initialized && !restoring) timer = setTimeout(report, 100); }, { capture: true, passive: true });
    addEventListener('pagehide', report);
    addEventListener('message', async event => {
      if (event.source !== parent || event.origin !== expectedOrigin || event.data?.frameId !== frameId) return;
      if (event.data.type === 'agent-harness:flush-scroll') { clearTimeout(timer); report(); return; }
      if (event.data.type !== 'agent-harness:init' || initialized || restoring) return;
      restoring = true;
      const scroll = event.data.scroll || {};
      if (document.readyState === 'loading') await new Promise(resolve => document.addEventListener('DOMContentLoaded', resolve, { once: true }));
      if (document.fonts) await Promise.race([document.fonts.ready, new Promise(resolve => setTimeout(resolve, 1500))]);
      await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
      for (const item of Array.isArray(scroll.containers) ? scroll.containers.slice(0, 20) : []) {
        // Only stable, bounded attribute selectors generated by this bridge.
        if (typeof item.anchor !== 'string' || item.anchor.length > 500 || !/^\[(?:id|data-testid|data-ah-scroll)=/.test(item.anchor)) continue;
        try { const nodes = document.querySelectorAll(item.anchor); if (nodes.length === 1) nodes[0].scrollTo(finite(item.x), finite(item.y)); } catch {}
      }
      scrollTo(finite(scroll.windowX), finite(scroll.windowY));
      initialized = true; restoring = false;
      send('ready'); report();
    });
    addEventListener('error', event => send('runtime-error', { message: String(event.message || 'Preview script failed').slice(0, 400) }));
    addEventListener('unhandledrejection', () => send('runtime-error', { message: 'An unhandled error occurred in the preview.' }));
    send('hello');
  })();`;
}
